# fly.toml app configuration file generated for voice-future-backend on 2025-04-09T22:18:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voice-future-backend'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENV = 'production'
  UVICORN_HOST = '0.0.0.0'
  UVICORN_PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
