# fly.toml app configuration file generated for voice-future-labs on 2025-04-09T22:24:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voice-future-labs'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'production'
  [build.args]
    VITE_BACKEND_URL = "wss://voice-future-backend.fly.dev/ws/call"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
